
---

stages:
  - validate
  - test
  - deploy

########################################################################################
# Simple workflow to demonstrate test and deploy
########################################################################################



yamllint:
  stage: validate
  image: registry.gitlab.com/pipeline-components/yamllint:latest
  script:
    - yamllint Ansible


deploy_dev:
  stage: deploy
  script:
    - cd Ansible
    - ansible-playbook -i inventory -e 'devices=development' playbooks/interface_update.yml
  needs: 
    - yamllint
  only:
    - main

test_dev:
  stage: test
  script:
    - cd pyATS
    - python3 pyATS_test.py dev 1
  needs: 
    - deploy_dev
  only:
    - main

deploy_prod:
  stage: deploy
  script:
    - cd Ansible
    - ansible-playbook -i inventory -e 'devices=production' playbooks/interface_update.yml
  needs: 
    - test_infra
  only:
    - main

test_prod:
  stage: test
  script:
    - cd pyATS
    - python3 pyATS_test.py prod 1
  needs: 
    - deploy_dev
  only:
    - main