site_name: Local Development to CICD
site_url: https://moore-automation.github.io/local_dev_to_cicd/
site_description: Lab Overview
site_author: Ed Moore & Frederic Wagner

repo_url: https://github.com/moore-automation/local_dev_to_cicd
edit_uri: blob/main/docs/

theme:
  name: material
  locale: en
  features:
    - content.code.copy
    - content.code.select

nav:
  - Home: index.md
  - Agenda: agenda.md
  - CI/CD Introduction: cicd_intro.md
  - Lab Setup: lab_setup_connect.md
  - Hands-On 1: hands_on_01.md

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
