site_name: Local Development to CICD
site_url: https://moore-automation.github.io/local_dev_to_cicd/
site_description: Lab Overview
site_author: Ed Moore & Frederic Wagner

repo_url: https://github.com/moore-automation/local_dev_to_cicd
edit_uri: blob/main/docs/

theme:
  name: material
  locale: en
  features:
    - content.code.copy
    - content.code.select

nav:
  - Home: index.md
  - Agenda: agenda.md
  - Lab Setup: lab_setup_connect.md
  - Lab Guide:
      - CI/CD Introduction: Lab_Guide/cicd_intro.md
      - Hands-On Part 1: 
          - Manual Work: Lab_Guide/hands_on_01_section_a.md
          - Tooling: Lab_Guide/hands_on_01_section_b.md
          - GitLab: Lab_Guide/hands_on_01_section_c.md          
      - Hands-On Part 2:
          - Linting & Stages: Lab_Guide/hands_on_02_section_a.md
          - Dev/Prod & Testing: Lab_Guide/hands_on_02_section_b.md       
                  

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
