---

- name: Cisco Interface Example
  hosts: '{{ devices | default("all") }}'
  gather_facts: false

  tasks:

    - name: Replaces device configuration
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.name  }}: {{ item.description }}"
            enabled: "{{ item.enabled }}"
      with_items: "{{ interfaces }}"

    - name: Check Running Configuration
      cisco.ios.ios_command:
        commands: "show run interface {{ item.name }}"
      register: post_change
      with_items: "{{ interfaces }}"

    - debug: var=post_change

    - debug: msg="Update Configuration - {{item.stdout}}"
      when: item.changed == true
      with_items: "{{post_change.results}}"
